In [1]:
import os
os.getcwd()

'C:\\Users\\MANEESHA\\Desktop\\final internship project'

In [2]:
os.chdir("C:/Users/MANEESHA/Desktop/final internship project")

In [3]:
os.getcwd()

'C:\\Users\\MANEESHA\\Desktop\\final internship project'

In [55]:
#importing libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sn
#importing datasets
df=pd.read_csv("train.csv")


In [5]:
df

id                                       comment_text  \
0       0000997932d777bf  Explanation\nWhy the edits made under my usern...   
1       000103f0d9cfb60f  D'aww! He matches this background colour I'm s...   
2       000113f07ec002fd  Hey man, I'm really not trying to edit war. It...   
3       0001b41b1c6bb37e  "\nMore\nI can't make any real suggestions on ...   
4       0001d958c54c6e35  You, sir, are my hero. Any chance you remember...   
...                  ...                                                ...   
159566  ffe987279560d7ff  ":::::And for the second time of asking, when ...   
159567  ffea4adeee384e90  You should be ashamed of yourself \n\nThat is ...   
159568  ffee36eab5c267c9  Spitzer \n\nUmm, theres no actual article for ...   
159569  fff125370e4aaaf3  And it looks like it was actually you who put ...   
159570  fff46fc426af1f9a  "\nAnd ... I really don't think you understand...   

        toxic  severe_toxic  obscene  threat  insult  identity_hate  
0           0             0        0       0       0              0  
1           0             0        0       0       0              0  
2           0             0        0       0       0              0  
3           0             0        0       0       0              0  
4           0             0        0       0       0              0  
...       ...           ...      ...     ...     ...            ...  
159566      0             0        0       0       0              0  
159567      0             0        0       0       0              0  
159568      0             0        0       0       0              0  
159569      0             0        0       0       0              0  
159570      0             0        0       0       0              0  

[159571 rows x 8 columns]

In [6]:
df.head(5000)

id                                       comment_text  \
0     0000997932d777bf  Explanation\nWhy the edits made under my usern...   
1     000103f0d9cfb60f  D'aww! He matches this background colour I'm s...   
2     000113f07ec002fd  Hey man, I'm really not trying to edit war. It...   
3     0001b41b1c6bb37e  "\nMore\nI can't make any real suggestions on ...   
4     0001d958c54c6e35  You, sir, are my hero. Any chance you remember...   
...                ...                                                ...   
4995  0d39d2eaa40a6241  "\n\nHello Marcruhwedell, and Welcome to Wikip...   
4996  0d3b57f3b2db3f03  ...that's why I did ....cheers,   (talk · cont...   
4997  0d3bb1f12d90a6a2  No, it's not a delayed reaction\n\nI just happ...   
4998  0d3be13abf1bec52  "\n\nA slight difference with you\nI have to d...   
4999  0d3c720db297b5a3  "\n\nNonsense.  The truth is NO schools give s...   

      toxic  severe_toxic  obscene  threat  insult  identity_hate  
0         0             0        0       0       0              0  
1         0             0        0       0       0              0  
2         0             0        0       0       0              0  
3         0             0        0       0       0              0  
4         0             0        0       0       0              0  
...     ...           ...      ...     ...     ...            ...  
4995      0             0        0       0       0              0  
4996      0             0        0       0       0              0  
4997      1             0        0       0       1              0  
4998      0             0        0       0       0              0  
4999      0             0        0       0       0              0  

[5000 rows x 8 columns]

In [7]:
types = ['toxic', 'severe_toxic', 'obscene', 'threat',
       'insult', 'identity_hate']

sampled_train1 = df[(df['toxic'] ==0) & (df['severe_toxic'] ==0) & (df['obscene'] ==0)
                       & (df['threat'] ==0) & (df['insult'] ==0) & (df['identity_hate'] ==0)][:20000]

sampled_train2 = df[(df['toxic'] !=0) | (df['severe_toxic'] !=0) | (df['obscene'] !=0) 
                | (df['threat'] !=0) | (df['insult'] !=0) | (df['identity_hate'] !=0)][:10000]

In [8]:
sampled_train = sampled_train2.append(sampled_train1)
sampled_train = sampled_train.sample(frac=1)

In [9]:
sampled_train.head(30000)

id                                       comment_text  \
11983  1fba1e79d24b1876  Summer of Love \n\nReversions reverted again a...   
19061  324dba37b71eb6aa  No about 50% of the kids that attended these s...   
19451  335a83439bc4584f  My recent updates that were deleted \n\nHello,...   
76821  cdb9be0e44ec35ab  Re:\nThe idiot keeps putting G-Unit Records on...   
13711  24353259f0c0f803  Wel I'm not calming down. I am just down here,...   
...                 ...                                                ...   
86265  e6b800d5d3fc1c35  GO SUCK A DICK YOU BITCH, YOU CANT SOTP ME CUN...   
2261   061ef06fdae32466  If you knew how many of these things pile in m...   
5193   0dd5a89e4cb2ad48  Whoops, missed the fact that I needed to log i...   
6924   127484754ce967a5  "**NM I belive. I've converted them as well.Wh...   
76507  ccd7d68d6a436708  Oh, shut up and fuck off, you asshole.  I'll b...   

       toxic  severe_toxic  obscene  threat  insult  identity_hate  
11983      0             0        0       0       0              0  
19061      0             0        0       0       0              0  
19451      0             0        0       0       0              0  
76821      1             0        0       0       1              0  
13711      0             0        0       0       0              0  
...      ...           ...      ...     ...     ...            ...  
86265      1             1        1       0       1              0  
2261       0             0        0       0       0              0  
5193       0             0        0       0       0              0  
6924       0             0        0       0       0              0  
76507      1             0        1       0       1              0  

[30000 rows x 8 columns]

In [10]:
toxic=sampled_train[:][:30000]

In [11]:
toxic.reset_index(inplace = True) 
  

In [12]:
toxic

index                id  \
0      11983  1fba1e79d24b1876   
1      19061  324dba37b71eb6aa   
2      19451  335a83439bc4584f   
3      76821  cdb9be0e44ec35ab   
4      13711  24353259f0c0f803   
...      ...               ...   
29995  86265  e6b800d5d3fc1c35   
29996   2261  061ef06fdae32466   
29997   5193  0dd5a89e4cb2ad48   
29998   6924  127484754ce967a5   
29999  76507  ccd7d68d6a436708   

                                            comment_text  toxic  severe_toxic  \
0      Summer of Love \n\nReversions reverted again a...      0             0   
1      No about 50% of the kids that attended these s...      0             0   
2      My recent updates that were deleted \n\nHello,...      0             0   
3      Re:\nThe idiot keeps putting G-Unit Records on...      1             0   
4      Wel I'm not calming down. I am just down here,...      0             0   
...                                                  ...    ...           ...   
29995  GO SUCK A DICK YOU BITCH, YOU CANT SOTP ME CUN...      1             1   
29996  If you knew how many of these things pile in m...      0             0   
29997  Whoops, missed the fact that I needed to log i...      0             0   
29998  "**NM I belive. I've converted them as well.Wh...      0             0   
29999  Oh, shut up and fuck off, you asshole.  I'll b...      1             0   

       obscene  threat  insult  identity_hate  
0            0       0       0              0  
1            0       0       0              0  
2            0       0       0              0  
3            0       0       1              0  
4            0       0       0              0  
...        ...     ...     ...            ...  
29995        1       0       1              0  
29996        0       0       0              0  
29997        0       0       0              0  
29998        0       0       0              0  
29999        1       0       1              0  

[30000 rows x 9 columns]

In [13]:
toxic['comment_text']

0        Summer of Love \n\nReversions reverted again a...
1        No about 50% of the kids that attended these s...
2        My recent updates that were deleted \n\nHello,...
3        Re:\nThe idiot keeps putting G-Unit Records on...
4        Wel I'm not calming down. I am just down here,...
                               ...                        
29995    GO SUCK A DICK YOU BITCH, YOU CANT SOTP ME CUN...
29996    If you knew how many of these things pile in m...
29997    Whoops, missed the fact that I needed to log i...
29998    "**NM I belive. I've converted them as well.Wh...
29999    Oh, shut up and fuck off, you asshole.  I'll b...
Name: comment_text, Length: 30000, dtype: object

In [14]:
toxic_labels = toxic[["toxic", "severe_toxic", "obscene", "threat", "insult", "identity_hate"]]
toxic_labels.head(15000)

toxic  severe_toxic  obscene  threat  insult  identity_hate
0          0             0        0       0       0              0
1          0             0        0       0       0              0
2          0             0        0       0       0              0
3          1             0        0       0       1              0
4          0             0        0       0       0              0
...      ...           ...      ...     ...     ...            ...
14995      0             0        0       0       0              0
14996      0             0        0       0       0              0
14997      0             0        0       0       0              0
14998      0             0        0       0       0              0
14999      0             0        0       0       0              0

[15000 rows x 6 columns]

In [15]:
import re
import nltk
nltk.download('wordnet')
from nltk.stem import WordNetLemmatizer
from nltk.corpus import stopwords
from string import punctuation
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()
lemmatizer = WordNetLemmatizer()
from textblob import TextBlob
X=[]
for i in range(0,30000):
       comment=toxic["comment_text"][i]
       comment = re.sub('[^a-zA-Z]', ' ', comment)
       comment = comment.lower()
       comment= comment.split()
       comment = [ps.stem(word) for word in comment if not word in set(stopwords.words('english'))]
       comment = ' '.join(comment)
       X.append(comment)

[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\MANEESHA\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


In [16]:
X[:100]

['summer love revers revert report new wikipedia edit articl ten year b accomplish music entertain author current year old recent celebr th year field c find effronter come back work page two day straight find eras peopl either born event took place b either one numer administr forum within wikipedia state articl heretofor deem dri stodgi sound may rewritten chatti style order appeal wider audienc page question alreadi report administr page protect well edit war interfer also revert report well',
 'kid attend school murder canadian govern knew wouldnt classifi genocid govern still let school stay kid abus kill',
 'recent updat delet hello thank much messag complet understand one updat delet consum affair site left messag talk page also see look page histori addit ambit page accolad taken without provid understand violat wiki saw comment work cite newsvideo understand possibl news cast avail youtub allow question ok input critic compani wiki page award mileston achiev independ sourc pro

In [17]:
!pip install pyspellchecker

In [18]:
from nltk.tokenize import sent_tokenize, word_tokenize 
token=[]
for i in X:
    token.append(word_tokenize(i))
    

In [19]:
token

[['summer',
  'love',
  'revers',
  'revert',
  'report',
  'new',
  'wikipedia',
  'edit',
  'articl',
  'ten',
  'year',
  'b',
  'accomplish',
  'music',
  'entertain',
  'author',
  'current',
  'year',
  'old',
  'recent',
  'celebr',
  'th',
  'year',
  'field',
  'c',
  'find',
  'effronter',
  'come',
  'back',
  'work',
  'page',
  'two',
  'day',
  'straight',
  'find',
  'eras',
  'peopl',
  'either',
  'born',
  'event',
  'took',
  'place',
  'b',
  'either',
  'one',
  'numer',
  'administr',
  'forum',
  'within',
  'wikipedia',
  'state',
  'articl',
  'heretofor',
  'deem',
  'dri',
  'stodgi',
  'sound',
  'may',
  'rewritten',
  'chatti',
  'style',
  'order',
  'appeal',
  'wider',
  'audienc',
  'page',
  'question',
  'alreadi',
  'report',
  'administr',
  'page',
  'protect',
  'well',
  'edit',
  'war',
  'interfer',
  'also',
  'revert',
  'report',
  'well'],
 ['kid',
  'attend',
  'school',
  'murder',
  'canadian',
  'govern',
  'knew',
  'wouldnt',
  'clas

# Bag of words

In [20]:
        
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=1500,stop_words='english')
X1 = cv.fit_transform(X).toarray()

In [21]:
ip_dim = X1.shape[1]


In [22]:
ip_dim


1500

In [23]:
X1.shape

(30000, 1500)

In [24]:
y = toxic_labels.values

In [25]:
y.shape

(30000, 6)

# Train and test split the data

In [26]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X1, y, test_size=0.20, random_state=42)

In [27]:
X_train

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [28]:
X_train.shape

(24000, 1500)

In [29]:
y_train.shape

(24000, 6)

In [30]:
X_test.shape

(6000, 1500)

In [31]:
y_test.shape

(6000, 6)

# ANN Model

In [32]:
from keras.models import Sequential
from keras.layers import Dense

Using TensorFlow backend.
C:\Users\MANEESHA\anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
C:\Users\MANEESHA\anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
C:\Users\MANEESHA\anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
C:\Users\MANEESHA\anaconda3\lib\site-packages\tensorflow\python\framewo

# Adding input layer,hidden layer and output layer

In [33]:
model = Sequential()

model.add(Dense(output_dim = 64, init = 'uniform', activation = 'relu', input_dim = ip_dim))#input layer

model.add(Dense(output_dim = 32, init = 'uniform', activation = 'relu'))#hidden layer

model.add(Dense(output_dim = 6, init = 'uniform', activation = 'sigmoid'))#output layer


C:\Users\MANEESHA\anaconda3\lib\site-packages\ipykernel_launcher.py:3: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", input_dim=1500, units=64, kernel_initializer="uniform")`
  This is separate from the ipykernel package so we can avoid doing imports until
C:\Users\MANEESHA\anaconda3\lib\site-packages\ipykernel_launcher.py:5: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", units=32, kernel_initializer="uniform")`
  """
C:\Users\MANEESHA\anaconda3\lib\site-packages\ipykernel_launcher.py:7: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="sigmoid", units=6, kernel_initializer="uniform")`
  import sys


# Compliling the model

In [34]:
model.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])


Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where


# Train and Test the model 


In [35]:
model.fit(X_train,y_train,batch_size=32,epochs=50)


Epoch 1/50
24000/24000 [==============================] - 2s 90us/step - loss: 0.2670 - accuracy: 0.9082
Epoch 2/50
24000/24000 [==============================] - 2s 80us/step - loss: 0.1676 - accuracy: 0.9403
Epoch 3/50
24000/24000 [==============================] - 2s 83us/step - loss: 0.1453 - accuracy: 0.9453
Epoch 4/50
24000/24000 [==============================] - 2s 82us/step - loss: 0.1346 - accuracy: 0.9475
Epoch 5/50
24000/24000 [==============================] - 2s 88us/step - loss: 0.1264 - accuracy: 0.9498
Epoch 6/50
24000/24000 [==============================] - 2s 87us/step - loss: 0.1194 - accuracy: 0.9529
Epoch 7/50
24000/24000 [==============================] - 2s 94us/step - loss: 0.1128 - accuracy: 0.9553
Epoch 8/50
24000/24000 [==============================] - 2s 91us/step - loss: 0.1065 - accuracy: 0.9578
Epoch 9/50
24000/24000 [==============================] - 2s 94us/step - loss: 0.1006 - accuracy: 0.9602
Epoch 10/50
24000/24000 [=============================

# optimize the model

In [36]:
y_pred=model.predict(X_test)

y_pred=y_pred>0.5

In [37]:
y_pred

array([[False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [ True, False, False, False,  True, False],
       ...,
       [False, False, False, False, False, False],
       [ True,  True,  True, False,  True, False],
       [False, False, False, False, False, False]])

In [38]:
y_test


array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 1, 0],
       ...,
       [0, 0, 0, 0, 0, 0],
       [1, 1, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]], dtype=int64)

In [39]:
score = model.evaluate(X_test, y_test)

print("Test Score:", score[0])
print("Test Accuracy:", score[1])

6000/6000 [==============================] - 0s 30us/step
Test Score: 1.0796208978494009
Test Accuracy: 0.9296667575836182


In [40]:
r=model.predict(cv.transform(["Hate you"]))

In [41]:
print(r)

[[0.99913853 0.0017764  0.04196924 0.04279017 0.17797928 0.16299841]]


In [42]:
r=r>0.5

r

array([[ True, False, False, False, False, False]])

In [43]:
r=model.predict(cv.transform(["he was clever"]))

In [44]:
r=r>0.5

r

array([[False, False, False, False, False, False]])

In [45]:
r=model.predict(cv.transform(["your are cruel"]))

In [46]:
r=r<0.5

r

array([[ True,  True,  True,  True,  True,  True]])

# Save The model

In [47]:
model.save("model.h5")