In [21]:
import os
os.chdir("C:/Users/MANEESHA/Desktop/final project 2020/dataset")
os.getcwd()

'C:\\Users\\MANEESHA\\Desktop\\final project 2020\\dataset'

In [22]:
import numpy as np
import pandas as pd


In [23]:
df=pd.read_csv("train.csv")
df

id                                       comment_text  \
0       0000997932d777bf  Explanation\r\nWhy the edits made under my use...   
1       000103f0d9cfb60f  D'aww! He matches this background colour I'm s...   
2       000113f07ec002fd  Hey man, I'm really not trying to edit war. It...   
3       0001b41b1c6bb37e  "\r\nMore\r\nI can't make any real suggestions...   
4       0001d958c54c6e35  You, sir, are my hero. Any chance you remember...   
...                  ...                                                ...   
159566  ffe987279560d7ff  ":::::And for the second time of asking, when ...   
159567  ffea4adeee384e90  You should be ashamed of yourself \r\n\r\nThat...   
159568  ffee36eab5c267c9  Spitzer \r\n\r\nUmm, theres no actual article ...   
159569  fff125370e4aaaf3  And it looks like it was actually you who put ...   
159570  fff46fc426af1f9a  "\r\nAnd ... I really don't think you understa...   

        toxic  severe_toxic  obscene  threat  insult  identity_hate  
0           0             0        0       0       0              0  
1           0             0        0       0       0              0  
2           0             0        0       0       0              0  
3           0             0        0       0       0              0  
4           0             0        0       0       0              0  
...       ...           ...      ...     ...     ...            ...  
159566      0             0        0       0       0              0  
159567      0             0        0       0       0              0  
159568      0             0        0       0       0              0  
159569      0             0        0       0       0              0  
159570      0             0        0       0       0              0  

[159571 rows x 8 columns]

In [24]:
df.head()

id                                       comment_text  toxic  \
0  0000997932d777bf  Explanation\r\nWhy the edits made under my use...      0   
1  000103f0d9cfb60f  D'aww! He matches this background colour I'm s...      0   
2  000113f07ec002fd  Hey man, I'm really not trying to edit war. It...      0   
3  0001b41b1c6bb37e  "\r\nMore\r\nI can't make any real suggestions...      0   
4  0001d958c54c6e35  You, sir, are my hero. Any chance you remember...      0   

   severe_toxic  obscene  threat  insult  identity_hate  
0             0        0       0       0              0  
1             0        0       0       0              0  
2             0        0       0       0              0  
3             0        0       0       0              0  
4             0        0       0       0              0

In [38]:
types = ['toxic', 'severe_toxic', 'obscene', 'threat',
       'insult', 'identity_hate']

sampled_train1 = df[(df['toxic'] ==0) & (df['severe_toxic'] ==0) & (df['obscene'] ==0)
                       & (df['threat'] ==0) & (df['insult'] ==0) & (df['identity_hate'] ==0)][:20000]

sampled_train2 = df[(df['toxic'] !=0) | (df['severe_toxic'] !=0) | (df['obscene'] !=0) 
                | (df['threat'] !=0) | (df['insult'] !=0) | (df['identity_hate'] !=0)][:10000]

In [39]:

sampled_train = sampled_train2.append(sampled_train1)
sampled_train = sampled_train.sample(frac=1)

In [40]:

sampled_train.head(15000)

id                                       comment_text  \
13066  2297ea8494718262  "\r\n\r\n Important notes \r\n Editors using t...   
12815  21f9880c38c476bf  Ian Watkins==\r\nIt's a realible source. It's ...   
13920  24bbb58a4a2e99af                         Removed due to censorshhip   
801    0220fd7637aa5f5c  "\r\n13:07 is when that part of the video show...   
1443   03dce741f43d2836  Current source \r\n\r\nI'm not sure what you'r...   
...                 ...                                                ...   
4632   0c45a5f53281e578  Looking back (Off Topic) \r\n\r\nI initially m...   
11264  1dd3125f1a496c1c  THE PERSONG SITTING TO MY RIGHT IS A STINKY VA...   
83913  e08852a8d69bc3db                    Deleted it again. Suck my dick.   
10062  1aa34914e4b0a6a7     or edited and reinserted to the main paragraph   
3350   0907dc323e7cc9c1  Help clarify an artice: John Stark \r\n\r\nI w...   

       toxic  severe_toxic  obscene  threat  insult  identity_hate  
13066      0             0        0       0       0              0  
12815      0             0        0       0       0              0  
13920      0             0        0       0       0              0  
801        0             0        0       0       0              0  
1443       0             0        0       0       0              0  
...      ...           ...      ...     ...     ...            ...  
4632       0             0        0       0       0              0  
11264      1             0        1       0       1              0  
83913      1             0        1       0       1              0  
10062      0             0        0       0       0              0  
3350       0             0        0       0       0              0  

[15000 rows x 8 columns]

In [41]:

toxic=sampled_train[:][:30000]

In [42]:

toxic.reset_index(inplace = True)

In [43]:

toxic

index                id  \
0      13066  2297ea8494718262   
1      12815  21f9880c38c476bf   
2      13920  24bbb58a4a2e99af   
3        801  0220fd7637aa5f5c   
4       1443  03dce741f43d2836   
...      ...               ...   
29995  13414  236a253d62f14eef   
29996   7619  1445e35486a2c87a   
29997   6667  11c69d939d257173   
29998   7362  13916479ef6e708c   
29999  17585  2e7e8edd78c47bdb   

                                            comment_text  toxic  severe_toxic  \
0      "\r\n\r\n Important notes \r\n Editors using t...      0             0   
1      Ian Watkins==\r\nIt's a realible source. It's ...      0             0   
2                             Removed due to censorshhip      0             0   
3      "\r\n13:07 is when that part of the video show...      0             0   
4      Current source \r\n\r\nI'm not sure what you'r...      0             0   
...                                                  ...    ...           ...   
29995  Twist And Shout \r\n\r\noriginally performed b...      0             0   
29996  "\r\nAccording to United States Census, ""The ...      0             0   
29997  According to this article of 6 Nov. 2009 , the...      0             0   
29998  "]] == Andre, I noticed you still haven't chan...      0             0   
29999  What the FUCK is your problem, bitch!!!!!!!!!!...      1             0   

       obscene  threat  insult  identity_hate  
0            0       0       0              0  
1            0       0       0              0  
2            0       0       0              0  
3            0       0       0              0  
4            0       0       0              0  
...        ...     ...     ...            ...  
29995        0       0       0              0  
29996        0       0       0              0  
29997        0       0       0              0  
29998        0       0       0              0  
29999        1       0       1              1  

[30000 rows x 9 columns]

In [44]:

toxic['comment_text']

0        "\r\n\r\n Important notes \r\n Editors using t...
1        Ian Watkins==\r\nIt's a realible source. It's ...
2                               Removed due to censorshhip
3        "\r\n13:07 is when that part of the video show...
4        Current source \r\n\r\nI'm not sure what you'r...
                               ...                        
29995    Twist And Shout \r\n\r\noriginally performed b...
29996    "\r\nAccording to United States Census, ""The ...
29997    According to this article of 6 Nov. 2009 , the...
29998    "]] == Andre, I noticed you still haven't chan...
29999    What the FUCK is your problem, bitch!!!!!!!!!!...
Name: comment_text, Length: 30000, dtype: object

In [45]:

toxic_labels = toxic[["toxic", "severe_toxic", "obscene", "threat", "insult", "identity_hate"]]
toxic_labels.head(30000)

toxic  severe_toxic  obscene  threat  insult  identity_hate
0          0             0        0       0       0              0
1          0             0        0       0       0              0
2          0             0        0       0       0              0
3          0             0        0       0       0              0
4          0             0        0       0       0              0
...      ...           ...      ...     ...     ...            ...
29995      0             0        0       0       0              0
29996      0             0        0       0       0              0
29997      0             0        0       0       0              0
29998      0             0        0       0       0              0
29999      1             0        1       0       1              1

[30000 rows x 6 columns]

In [46]:
import re
import nltk
#nltk.download('wordnet')
from nltk.stem import WordNetLemmatizer
from nltk.corpus import stopwords
from string import punctuation
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()
lemmatizer = WordNetLemmatizer()
X=[]
for i in range(0,30000):
        comment = toxic['comment_text'][i]
        comment = re.sub('[^a-zA-Z]', ' ', comment)
        comment = comment.lower()
        comment = comment.split()
        comment = [ps.stem(word) for word in comment if not word in set(stopwords.words('english'))]
        comment = ' '.join(comment)
        X.append(comment)

In [47]:
X[:8]

['import note editor use ip address exclus privat individu edit ip address constru way repres otherwis speak behalf vangent gdit gener dynam thank introduct pleas note user previous contribut least one ip address migrat use ip address self welcom style background color f fffa pad cellpad style border px solid background color f fffa vertic align top color hello welcom wikipedia thank contribut free encyclopedia decid need help check get help ask talk page place talk page ask question pleas rememb sign name talk page use four tild click shown automat produc usernam date also pleas best alway fill edit summari field edit use link facilit involv happi edit width style background color f fffa style width border px solid ffffff background color f fffa vertic align top width cellpad cellspac style vertic align top background color f fffa get start style color tutori five pillar get mentor edit page upload use imag creat first articl intuit guid wikipedia articl creation wizard get help style

In [48]:
from nltk.tokenize import sent_tokenize, word_tokenize 
token=[]
for i in X:
    token.append(word_tokenize(i))

In [49]:
token

[['import',
  'note',
  'editor',
  'use',
  'ip',
  'address',
  'exclus',
  'privat',
  'individu',
  'edit',
  'ip',
  'address',
  'constru',
  'way',
  'repres',
  'otherwis',
  'speak',
  'behalf',
  'vangent',
  'gdit',
  'gener',
  'dynam',
  'thank',
  'introduct',
  'pleas',
  'note',
  'user',
  'previous',
  'contribut',
  'least',
  'one',
  'ip',
  'address',
  'migrat',
  'use',
  'ip',
  'address',
  'self',
  'welcom',
  'style',
  'background',
  'color',
  'f',
  'fffa',
  'pad',
  'cellpad',
  'style',
  'border',
  'px',
  'solid',
  'background',
  'color',
  'f',
  'fffa',
  'vertic',
  'align',
  'top',
  'color',
  'hello',
  'welcom',
  'wikipedia',
  'thank',
  'contribut',
  'free',
  'encyclopedia',
  'decid',
  'need',
  'help',
  'check',
  'get',
  'help',
  'ask',
  'talk',
  'page',
  'place',
  'talk',
  'page',
  'ask',
  'question',
  'pleas',
  'rememb',
  'sign',
  'name',
  'talk',
  'page',
  'use',
  'four',
  'tild',
  'click',
  'shown',
  'a

In [62]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=1000,stop_words='english')
X1 = cv.fit_transform(X).toarray()

In [63]:
X1.shape

(30000, 1000)

In [64]:
y = toxic_labels.values

In [65]:
y.shape

(30000, 6)

# splitting the data


In [115]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X1, y, test_size=0.20, random_state=0)

In [116]:
X_train

array([[0, 0, 0, ..., 0, 2, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [117]:
X_train.shape

(24000, 1000)

In [118]:
y_train.shape

(24000, 6)

In [119]:
y_test.shape

(6000, 6)

In [120]:
X_test.shape


(6000, 1000)

# ANN model

In [121]:
from keras.models import Sequential
from keras.layers import Dense

In [128]:

model = Sequential()

model.add(Dense(output_dim = 64, init = 'uniform', activation = 'relu', input_dim = 1000))

model.add(Dense(output_dim = 32, init = 'uniform', activation = 'relu'))

model.add(Dense(output_dim = 6, init = 'uniform', activation = 'sigmoid'))

C:\Users\MANEESHA\anaconda3\lib\site-packages\ipykernel_launcher.py:3: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", input_dim=1000, units=64, kernel_initializer="uniform")`
  This is separate from the ipykernel package so we can avoid doing imports until
C:\Users\MANEESHA\anaconda3\lib\site-packages\ipykernel_launcher.py:5: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", units=32, kernel_initializer="uniform")`
  """
C:\Users\MANEESHA\anaconda3\lib\site-packages\ipykernel_launcher.py:7: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="sigmoid", units=6, kernel_initializer="uniform")`
  import sys


In [129]:
model.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

In [130]:
model.fit(X_train,y_train,batch_size=128,epochs=30)

Epoch 1/30
24000/24000 [==============================] - 1s 38us/step - loss: 0.3866 - accuracy: 0.8766
Epoch 2/30
24000/24000 [==============================] - 1s 27us/step - loss: 0.2196 - accuracy: 0.9160
Epoch 3/30
24000/24000 [==============================] - 1s 26us/step - loss: 0.1801 - accuracy: 0.9347
Epoch 4/30
24000/24000 [==============================] - 1s 26us/step - loss: 0.1635 - accuracy: 0.9398
Epoch 5/30
24000/24000 [==============================] - 1s 27us/step - loss: 0.1526 - accuracy: 0.9418
Epoch 6/30
24000/24000 [==============================] - 1s 27us/step - loss: 0.1474 - accuracy: 0.9431
Epoch 7/30
24000/24000 [==============================] - 1s 28us/step - loss: 0.1440 - accuracy: 0.9438
Epoch 8/30
24000/24000 [==============================] - 1s 28us/step - loss: 0.1397 - accuracy: 0.9450
Epoch 9/30
24000/24000 [==============================] - 1s 26us/step - loss: 0.1362 - accuracy: 0.9459
Epoch 10/30
24000/24000 [==============================

In [131]:
r=model.predict(cv.transform(["She is very good"]))

In [132]:
r

array([[0.07212356, 0.00180882, 0.01008654, 0.0079861 , 0.0108647 ,
        0.00455316]], dtype=float32)

In [133]:
r=model.predict(cv.transform(["fuck"]))

In [134]:
r

array([[0.9988961 , 0.19184127, 0.99400747, 0.0184963 , 0.71696967,
        0.01560419]], dtype=float32)

In [135]:
r=model.predict(cv.transform(["bad"]))

In [136]:
r

array([[0.39456865, 0.00481269, 0.05561447, 0.01239207, 0.10569102,
        0.00467366]], dtype=float32)

In [137]:
r=model.predict(cv.transform(["fuck off"]))

In [138]:
r

array([[0.9988961 , 0.19184127, 0.99400747, 0.0184963 , 0.71696967,
        0.01560419]], dtype=float32)